import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/settings_provider.dart';

class AppLanguage {
  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'My First App',
      'home': 'Home',
      'lamp': 'Lamp',
      'gallery': 'Gallery',
      'profile': 'Profile',
      'explore_listview': 'Explore ListView',
      'search_hint': 'Search items...',
      'add_new_item': 'Add New Item',
      'item_name': 'Item Name',
      'cancel': 'Cancel',
      'save': 'Save',
      'smart_control': 'Smart Control',
      'lamp_active': 'Lamp Active',
      'lamp_inactive': 'Lamp Inactive',
      'intensity': 'Intensity',
      'logout': 'Log Out',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'edit_profile': 'Edit Profile',
      'welcome': 'Welcome',
      'please_login': 'Please login to your account',
      'username': 'Username',
      'password': 'Password',
      'login': 'Login',
      'no_account': 'No account? Register now',
      'signup': 'Sign Up',
      'create_account': 'Create your new account',
      'confirm_password': 'Confirm Password',
      'register': 'Register',
      'lamp_desc_on': 'Lighting the room optimally.',
      'lamp_desc_off': 'Save energy by turning off the lamp.',
      'full_name': 'Full Name',
      'bio': 'Bio',
      'register_success': 'Registration successful! Please login.',
      'username_required': 'Username is required',
      'password_required': 'Password is required',
      'min_3_chars': 'Minimum 3 characters',
      'min_6_chars': 'Minimum 6 characters',
      'password_mismatch': 'Passwords do not match',
      'listview_default': '1. ListView Default',
      'listview_default_desc': 'Best for static menus & small data.',
      'app_info': 'App Information',
      'help_center': 'Help Center',
      'general_settings': 'General Settings',
      'listview_builder': '2. ListView.builder (Dynamic)',
      'listview_builder_desc': 'Data stored permanently in Sembast.',
      'listview_separated': '3. ListView.separated',
      'listview_separated_desc': 'Clean with visual separators between items.',
      'transaction': 'Transaction',
      'paid': 'Paid',
      'detail_open': 'Detail {name} opened',
      'gridview_title': 'GridView Material',
      'gridview_count': '1. GridView.count',
      'gridview_count_desc': 'Fixed column count (Dynamic from API)',
      'gridview_builder': '2. GridView.builder',
      'gridview_builder_desc': 'Efficient for large data (Dynamic from API)',
      'gridview_extent': '3. GridView.extent',
      'gridview_extent_desc': 'Fixed item width (Dynamic from API)',
      'try_again': 'Try Again',
      'change_photo': 'Change Photo',
      'crop_photo': 'Crop Photo',
      'crop_save': 'Save',
      'crop_hint': 'Pinch to zoom, drag to adjust position',
    },
    'id': {
      'app_title': 'Aplikasi Pertama Saya',
      'home': 'Beranda',
      'lamp': 'Lampu',
      'gallery': 'Galeri',
      'profile': 'Profil',
      'explore_listview': 'Eksplorasi ListView',
      'search_hint': 'Cari item...',
      'add_new_item': 'Tambah Item Baru',
      'item_name': 'Nama Item',
      'cancel': 'Batal',
      'save': 'Simpan',
      'smart_control': 'Kendali Pintar',
      'lamp_active': 'Lampu Aktif',
      'lamp_inactive': 'Lampu Nonaktif',
      'intensity': 'Intensitas',
      'logout': 'Keluar',
      'dark_mode': 'Mode Gelap',
      'language': 'Bahasa',
      'edit_profile': 'Edit Profil',
      'welcome': 'Selamat Datang',
      'please_login': 'Silakan masuk ke akun Anda',
      'username': 'Username',
      'password': 'Password',
      'login': 'Masuk',
      'no_account': 'Belum punya akun? Daftar sekarang',
      'signup': 'Daftar',
      'create_account': 'Buat akun baru kamu sekarang',
      'confirm_password': 'Konfirmasi Password',
      'register': 'Daftar',
      'lamp_desc_on': 'Menerangi ruangan dengan optimal.',
      'lamp_desc_off': 'Hemat energi dengan mematikan lampu.',
      'full_name': 'Nama Lengkap',
      'bio': 'Bio',
      'register_success': 'Pendaftaran berhasil! Silakan login.',
      'username_required': 'Username wajib diisi',
      'password_required': 'Password wajib diisi',
      'min_3_chars': 'Minimal 3 karakter',
      'min_6_chars': 'Minimal 6 karakter',
      'password_mismatch': 'Password tidak sama',
      'listview_default': '1. ListView Default',
      'listview_default_desc': 'Terbaik untuk menu statis & data sedikit.',
      'app_info': 'Informasi Aplikasi',
      'help_center': 'Pusat Bantuan',
      'general_settings': 'Pengaturan Umum',
      'listview_builder': '2. ListView.builder (Dynamic)',
      'listview_builder_desc': 'Data tersimpan secara permanen di Sembast.',
      'listview_separated': '3. ListView.separated',
      'listview_separated_desc': 'Rapi dengan pembatas visual antar item.',
      'transaction': 'Transaksi',
      'paid': 'Lunas',
      'detail_open': 'Detail {name} terbuka',
      'gridview_title': 'Materi GridView',
      'gridview_count': '1. GridView.count',
      'gridview_count_desc': 'Jumlah kolom tetap (Dinamis dari API)',
      'gridview_builder': '2. GridView.builder',
      'gridview_builder_desc': 'Efisien untuk data besar (Dinamis dari API)',
      'gridview_extent': '3. GridView.extent',
      'gridview_extent_desc': 'Ukuran lebar item tetap (Dinamis dari API)',
      'try_again': 'Coba Lagi',
      'change_photo': 'Ganti Foto',
      'crop_photo': 'Potong Foto',
      'crop_save': 'Simpan',
      'crop_hint': 'Cubit untuk zoom, geser untuk atur posisi',
    },
  };

  static String t(BuildContext context, String key) {
    final locale = Provider.of<SettingsProvider>(context).locale.languageCode;
    return _localizedValues[locale]?[key] ?? key;
  }
}
